version: '3'
services:
  langchain:
    build:
      dockerfile: Dockerfile
      context: ..
    volumes:
   # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/app
    networks:
      - langchain-network 

networks:
  langchain-network:
    driver: bridge
